name = "MyITensorsPkg"
uuid = "b33b1a07-6eec-4458-8efd-3d86e8afc6ba"
authors = ["Matthew Fishman <mfishman@flatironinstitute.org> and contributors"]
version = "0.1.0"

[deps]
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"

[compat]
ITensors = "0.1"
julia = "1"

[extras]
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ITensors"]
